### ISSUE TITLE
Replica Set connection syntax

### ISSUE THREAD

**Issue by brandonhilkert** [mongomapper/mongomapper#412]
What is correct replicate set syntax?

```
production:
  database: db1
  hosts:
  - - db1.domain.com
    - 10008
  - - db2.domain.com
    - 10009
```

We have a syntax like the above and are getting this message with the latest Mongo driver.

```
Initiating a ReplSetConnection with seeds passed as individual [host, port] array arguments is deprecated.
Please specify hosts as an array of 'host:port' strings; the old format will be removed in v2.0
Loading production environment (Rails 3.2.1)
```
