### ISSUE TITLE
Mongo_mapper not using my parameters from mongo.yml

### ISSUE THREAD

**Issue by camdub** [mongomapper/mongomapper#464]
My mongo.yml document is as follows: 

```
development:
  uri: <%= ENV['MONGODB_DEV_URI'] %>

test:
  uri: <%= ENV['MONGODB_DEV_URI'] %>

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
```

When I run the `rails c` command to test this, it gives me the following error: 
`connection.rb:440:in 'connect': Failed to connect to a master node at localhost:27017 (Mongo::ConnectionFailure)`

It looks like its not even attempting to use the uri values (all URIs are for MongoHQ databases). Does only production support the uri value?

Update: When I add host and port attributes to my development section of the yml file, it connects correctly. Also, adding a puts line in the gem where the above error is coming from (connection.rb in mongo_mapper), the uri value is nil. I will attempt to figure out the issue and submit a pull request if necessary.
