### ISSUE TITLE
Configuring pool_size with uri

### ISSUE THREAD

**Issue by we4tech** [mongomapper/mongomapper#554]
Hi there, Thanks for such awesome gem, keep up the good works :+1: - 

Btw, i was trying to set pool_size by passing as query string also as options, just to see which one picks up :)

``` YAML
production:
  uri: ......?pool_size=15
  options:
    pool_size: 15
```

Seems like it doesn't work, this way unless I explicitly pass during `MongoMapper.setup` call.

So this won't pick up the configuration 

``` ruby
MongoMapper.setup(config, env)
```

Instead this one should work.

``` ruby
MongoMapper.setup(config, env, {pool_size: 15})
```

Just wondering is there any specific reason why this feature is not supported ? or am I missing something obvious :)

Best wishes,
