### ISSUE TITLE
Poor support for ReplicaSets

### ISSUE THREAD

**Issue by PurpleBooth** [mongomapper/mongomapper#625]
Most modern MongoDB configurations use ReplicaSets there is little or no support for this in mongomapper.

Support needed:
* Support URIs with ReplicaSets
* Support ReplicaSet names from verbose config

The URI parameter in the config currently fails when you try to pass a multi-host URI to it.
```
mongodb://$USERNAME:$PASSWORD@mymongo-1:39113,mymongo-2:39113/mydatabase?replicaSet=my-replicaset"
```

will result in this error:

```
I, [2015-11-11T13:09:17.214743 #6]  INFO -- : Refreshing Gem list
/usr/lib/ruby/2.1.0/uri/generic.rb:214:in `initialize': the scheme mongodb does not accept registry part: $USERNAME:$PASSWORD@mymongo-1:39113,mymongo-2:39113 (or bad hostname?) (URI::InvalidURIError)
	from /usr/lib/ruby/2.1.0/uri/common.rb:218:in `new'
	from /usr/lib/ruby/2.1.0/uri/common.rb:218:in `parse'
	from /usr/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
	from /var/lib/gems/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb:57:in `config_for_environment'
	from /var/lib/gems/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb:70:in `connect'
	from /var/lib/gems/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb:99:in `setup'
	from /var/lib/gems/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/railtie.rb:48:in `block in <class:Railtie>'
```

There is a multi-host config that looks something like"

```
  hosts:
      - <%= ENV['MONGODB_HOST_1'] %>
      - <%= ENV['MONGODB_HOST_2'] %>
  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
  database: <%= ENV['MONGODB_DATABASE'] %>
```

However it doesn't allow you to set the replicaSet

**Comment by fcheung** [comment]
Doesn't
``` yaml
hosts: 
  - host1
  - host2
options:
  :name: replica_set_name
```
work?
